# Generated by Django 5.1.2 on 2024-10-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0002_rectangle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='sig',
        ),
    ]
